### ISSUE TITLE
Installation error via zpm in Windows

### ISSUE THREAD

**Issue by SergeyMi37** [diashenrique/iris-on-fhir#1]
![image](https://user-images.githubusercontent.com/18187317/120372595-0ed2d500-c320-11eb-9603-324663a81c6a.png)

**Comment by SergeyMi37** [comment]
Apparently the project only works in docker?

**Comment by diashenrique** [comment]
Hi @SergeyMi37 
Thanks for pointing that out. 
We're in working on a hurry to deliver other features, but we'll fix that to work on Windows as well. 
I want to thank you again for your collaboration with us as usual.
